from enum import Enum


class LogLevels(Enum):
    TRACE = 0
    DEBUG = 1
    INFO = 2
    WARN = 3
    ERROR = 4
    FATAL = 5
    ALL = 6
    NONE = 7


class SequenceAcquisitionOptions(Enum):
    HIS_SEQ_TWO_BUFFERS = 0x1
    HIS_SEQ_ONE_BUFFER = 0x2
    HIS_SEQ_AVERAGE = 0x4
    HIS_SEQ_DEST_ONE_FRAME = 0x8
    HIS_SEQ_COLLATE = 0x10
    HIS_SEQ_CONTINUOUS = 0x100
    HIS_SEQ_LEAKAGE = 0x1000
    HIS_SEQ_NONLINEAR = 0x2000
    HIS_SEQ_AVERAGESEQ = 0x4000
    HIS_SEQ_PREVIEW = 0x8000


class Triggers(Enum):
    HIS_SYNCMODE_SOFT_TRIGGER = 1
    HIS_SYNCMODE_INTERNAL_TIMER = 2
    HIS_SYNCMODE_EXTERNAL_TRIGGER = 3
    HIS_SYNCMODE_FREE_RUNNING = 4
    HIS_SYNCMODE_AUTO_TRIGGER = 8
    HIS_SYNCMODE_EXTERNAL_TRIGGER_FG = 16
